// This Source Code Form is subject to the terms of the Plezix Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! This file contains the Generated JOG Factory for the runtime-registration
//! of Glean metrics in Plezix on Glean.
//! You probably should just ignore stuff in here and ask on the
//! [#glean Matrix channel](https://chat.mozilla.org/#/room/#glean:mozilla.org)
//! if you have questions.
//!
//! Most of the contents of this module are generated by
//! `toolkit/components/glean/build_scripts/glean_parser_ext/run_glean_parser.py`

include!(mozbuild::objdir_path!(
    "toolkit/components/glean/api/src/factory.rs"
));
